# Generated by Django 4.2.7 on 2023-11-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0002_newsletter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="subject",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
