# Generated by Django 4.2.7 on 2023-12-16 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0005_alter_content_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="subject",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
