# Generated by Django 4.2.7 on 2023-12-16 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0006_alter_content_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="subject",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
