# Generated by Django 4.2.7 on 2023-12-10 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0013_comments_post"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comments",
            options={"ordering": ["-created_date"]},
        ),
    ]
