# Generated by Django 4.2.7 on 2024-03-16 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0015_post_login_require"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comments",
            options={"ordering": ("-created_date",)},
        ),
    ]
